import User from '../models/User.js';
import Team from '../models/Team.js';
import Match from '../models/Match.js';

// Random matchmaking: group solo-queued players into teams and create matches
export const runMatchmaking = async (teamSize = 5) => {
  // 1. Get all queued players
  const queuedPlayers = await User.find({ inQueue: true, team: null }).sort({ skillLevel: 1 });

  if (queuedPlayers.length < teamSize * 2) {
    return {
      success: false,
      message: `Need at least ${teamSize * 2} players in queue. Currently: ${queuedPlayers.length}`,
    };
  }

  // 2. Distribute players by skill for balance
  const skillOrder = { beginner: 1, intermediate: 2, pro: 3 };
  const sorted = [...queuedPlayers].sort((a, b) => skillOrder[a.skillLevel] - skillOrder[b.skillLevel]);

  // 3. Create teams using serpentine draft
  const teamsToCreate = Math.floor(sorted.length / teamSize);
  const actualTeams = teamsToCreate % 2 === 0 ? teamsToCreate : teamsToCreate - 1; // Need even number
  const groups = Array.from({ length: actualTeams }, () => []);

  let idx = 0;
  for (let i = 0; i < actualTeams * teamSize; i++) {
    const round = Math.floor(i / actualTeams);
    const pos = round % 2 === 0 ? i % actualTeams : actualTeams - 1 - (i % actualTeams);
    groups[pos].push(sorted[idx++]);
  }

  // 4. Create team entries and assign players
  const createdTeams = [];
  const adjectives = ['Thunder', 'Shadow', 'Iron', 'Frost', 'Storm', 'Blaze', 'Arctic', 'Venom', 'Cosmic', 'Phantom'];
  const nouns = ['Wolves', 'Hawks', 'Titans', 'Knights', 'Vikings', 'Panthers', 'Dragons', 'Strikers', 'Warriors', 'Legends'];

  for (const group of groups) {
    const teamName = `${adjectives[Math.floor(Math.random() * adjectives.length)]} ${nouns[Math.floor(Math.random() * nouns.length)]}`;
    const code = await Team.generateCode();

    const team = await Team.create({
      name: teamName,
      code,
      captain: group[0]._id,
      players: group.map(p => p._id),
      maxPlayers: teamSize,
      isAutoGenerated: true,
    });

    // Update players
    for (const player of group) {
      await User.findByIdAndUpdate(player._id, { team: team._id, inQueue: false });
    }

    createdTeams.push(team);
  }

  // 5. Pair teams into matches
  const matches = [];
  const locations = ['HockeyHub Arena', 'Turf Stadium', 'Field Palace', 'Summer Dome', 'Greenwood Pitch'];

  for (let i = 0; i < createdTeams.length; i += 2) {
    const matchDate = new Date(Date.now() + (i / 2 + 1) * 24 * 60 * 60 * 1000); // Days from now
    const hours = [14, 16, 18, 20];
    const hour = hours[Math.floor(Math.random() * hours.length)];

    const match = await Match.create({
      teamA: createdTeams[i]._id,
      teamB: createdTeams[i + 1]._id,
      date: matchDate,
      time: `${hour}:00`,
      location: locations[Math.floor(Math.random() * locations.length)],
    });
    matches.push(match);
  }

  // Mark remaining queued players (those not assigned)
  // They stay in queue for the next round

  return {
    success: true,
    teamsCreated: createdTeams.length,
    matchesCreated: matches.length,
    playersAssigned: actualTeams * teamSize,
    playersRemaining: queuedPlayers.length - actualTeams * teamSize,
  };
};
